// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MyFirstRazorWebPage.Migrations
{
    [DbContext(typeof(RazorPagesMovieContext))]
    [Migration("20200807115135_Modules")]
    partial class Modules
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("MyFirstRazorWebPage.Models.AdminUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("AdminUser");
                });

            modelBuilder.Entity("MyFirstRazorWebPage.Models.Modules", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModSemester")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("MyFirstRazorWebPage.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAdd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
